_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 3
                - 8
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "8":
                - 5
            "10":
                - 9
                - 17
            "12": 0.19.11
            "13": linux-x86_64
dropout1:
    value: 0.3
dropout2:
    value: 0.3
dropout3:
    value: 0.2
epochs:
    value: 50
patience:
    value: 5
